/* Generated By:JavaCC: Do not edit this line. LaTeXParserConstants.java */
package org.jbibtex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LaTeXParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BACKSLASH = 1;
  /** RegularExpression Id. */
  int LBRACE = 2;
  /** RegularExpression Id. */
  int RBRACE = 3;
  /** RegularExpression Id. */
  int WHITESPACE = 4;
  /** RegularExpression Id. */
  int SPECIAL = 5;
  /** RegularExpression Id. */
  int NON_SPECIAL = 6;
  /** RegularExpression Id. */
  int ASCII_LETTER = 7;
  /** RegularExpression Id. */
  int ASCII_DIGIT = 8;
  /** RegularExpression Id. */
  int LATIN_SUPPLEMENT = 9;
  /** RegularExpression Id. */
  int UNICODE_LETTER = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\\\"",
    "\"{\"",
    "\"}\"",
    "<WHITESPACE>",
    "<SPECIAL>",
    "<NON_SPECIAL>",
    "<ASCII_LETTER>",
    "<ASCII_DIGIT>",
    "<LATIN_SUPPLEMENT>",
    "<UNICODE_LETTER>",
  };

}
